/**
 * Collection card-art manifest — the set of collection slugs that have generated
 * background artwork at `public/brand/collection-cards/<slug>.webp`.
 *
 * AUTO-GENERATED by `scripts/generate-collection-card-art.ts` (Kie.ai Nano
 * Banana Pro). Do not edit by hand — re-run `npm run cards:generate`.
 *
 * This is the BACKGROUND set, distinct from `collection-covers.ts`: text-free,
 * contrast-capped art that sits behind the card copy. The /collections brand
 * cards read this to decide whether to render artwork or stay on the plain card
 * surface, so a missing file degrades gracefully instead of 404-ing.
 */
export const COLLECTION_CARD_ART_SLUGS: ReadonlySet<string> = new Set<string>([
  "miffy",
  "sanrio",
  "tamagotchi",
]);

/**
 * Cache-busting stamp, refreshed on every generation run. Filenames are stable,
 * so this query param is what forces browsers to re-fetch regenerated art.
 */
export const COLLECTION_CARD_ART_VERSION = "ms76ftmx";

/** Public path to a collection's card background (cache-busted). */
export function collectionCardArtSrc(slug: string): string {
  return `/brand/collection-cards/${slug}.webp?v=${COLLECTION_CARD_ART_VERSION}`;
}
