/**
 * Collection cover manifest — the set of collection slugs that have a
 * generated hero image at `public/brand/collections/<slug>.webp`.
 *
 * AUTO-GENERATED by `scripts/generate-collection-covers.ts` (Kie.ai Nano Banana
 * Pro). Do not edit by hand — re-run `npm run covers:generate` to refresh it.
 *
 * The `CategoryRail` reads this to decide whether to show a rich cover photo or
 * fall back to a clean on-brand gradient tile, so a missing image never 404s.
 */
export const COLLECTION_COVER_SLUGS: ReadonlySet<string> = new Set<string>([
  "chiikawa",
  "cinnamoroll",
  "disney",
  "hello-kitty",
  "keroppi",
  "kuromi",
  "little-twin-stars",
  "magsafe",
  "miffy",
  "monchhichi",
  "my-melody",
  "originals",
  "pochacco",
  "pompompurin",
  "rilakkuma",
  "sanrio",
  "tamagotchi",
  "toy-story",
]);

/**
 * Cache-busting stamp, refreshed on every generation run. Because covers keep
 * stable filenames, this query param forces browsers to re-fetch the art
 * whenever it's regenerated instead of serving a stale cached image.
 */
export const COLLECTION_COVERS_VERSION = "mtxx9fb8";

/** Public path to a collection's generated cover image (cache-busted). */
export function collectionCoverSrc(slug: string): string {
  return `/brand/collections/${slug}.webp?v=${COLLECTION_COVERS_VERSION}`;
}
