/**
 * Device cover manifest — the set of device ids that have a generated hero
 * banner at `public/brand/device-covers/<id>.webp`.
 *
 * AUTO-GENERATED by `scripts/generate-device-covers.ts` (Kie.ai Nano Banana
 * Pro). Do not edit by hand — re-run `npm run devices:generate` to refresh it.
 *
 * The homepage "Shop by device" grid reads this to show a rich banner, falling
 * back to a clean gradient tile so a missing image never 404s.
 */
export const DEVICE_COVER_IDS: ReadonlySet<string> = new Set<string>([
  "airpods",
  "apple-accessories",
  "apple-watch",
  "ipad",
  "iphone",
  "macbook",
]);

/**
 * Cache-busting stamp, refreshed on every generation run so browsers re-fetch
 * covers when the art changes (the filenames stay stable).
 */
export const DEVICE_COVERS_VERSION = "mrydh35f";

/** Public path to a device's generated cover banner (cache-busted). */
export function deviceCoverSrc(id: string): string {
  return `/brand/device-covers/${id}.webp?v=${DEVICE_COVERS_VERSION}`;
}
