/**
 * Generate branded "Shop the universe" cover images — one per collection — with
 * Kie.ai's Nano Banana Pro (Gemini 3 Pro Image), then downscale to web-ready
 * WebP and refresh the cover manifest.
 *
 *   npm run covers:generate                         # generate any missing covers
 *   npm run covers:generate -- --force              # regenerate every cover
 *   npm run covers:generate -- --slugs originals    # one (or a comma-list)
 *   npx tsx scripts/generate-collection-covers.ts --slugs originals --from-file path.png
 *
 * npm intercepts `--only` as its own config — never pass `--only` through
 * `npm run`. Use `--slugs` (or call tsx directly).
 *
 * Output: public/brand/collections/<slug>.webp
 * Manifest: src/lib/brand/collection-covers.ts (slugs that now have a cover)
 *
 * The prompts render a UNIFIED, on-brand look: flat 2D pixel / 8-bit sprites,
 * a centred arcade wordmark, and a pastel gradient in each collection's accent
 * colour, so the rail reads as one designer set rather than a grab-bag.
 * Node-only. API generation requires KIE_API_KEY; `--from-file` does not.
 */
import { config } from "dotenv";
config({ path: ".env.local" });

import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import {
  flattenTaxonomy,
  RAIL_HIDDEN_SLUGS,
} from "../src/lib/catalog/collections-config";
import {
  buildCollectionCoverPrompt,
  COLLECTION_COVER_ASPECT,
  hasBespokeCoverTheme,
} from "./lib/collection-cover-themes";
import { generateImage, requireKieApiKey } from "./lib/nano-banana";

const OUT_WIDTH = 1024; // retina-crisp for a ~320px banner, tiny on disk as WebP
const OUT_DIR = path.join(process.cwd(), "public", "brand", "collections");
const MANIFEST = path.join(
  process.cwd(),
  "src",
  "lib",
  "brand",
  "collection-covers.ts",
);
/** One retry: the gateway's safety filter is stochastic on mascot-adjacent art. */
const MAX_ATTEMPTS = 2;

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 ? process.argv[i + 1] : undefined;
}
const FORCE = process.argv.includes("--force");
/** npm steals `--only`; `--slugs` is the supported flag. `--only` still works via tsx. */
const SLUGS = (arg("slugs") ?? arg("only") ?? "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);
/**
 * Encode a local PNG/WebP through the same Sharp pipeline instead of calling
 * the API — used to ship a chosen candidate (style-matched against the rail)
 * without paying for another generation.
 */
const FROM_FILE = arg("from-file");

function writeManifest(slugs: string[], version: string): void {
  const list = [...slugs].sort();
  const entries = list.map((s) => `  ${JSON.stringify(s)},`).join("\n");
  const body = `/**
 * Collection cover manifest — the set of collection slugs that have a
 * generated hero image at \`public/brand/collections/<slug>.webp\`.
 *
 * AUTO-GENERATED by \`scripts/generate-collection-covers.ts\` (Kie.ai Nano Banana
 * Pro). Do not edit by hand — re-run \`npm run covers:generate\` to refresh it.
 *
 * The \`CategoryRail\` reads this to decide whether to show a rich cover photo or
 * fall back to a clean on-brand gradient tile, so a missing image never 404s.
 */
export const COLLECTION_COVER_SLUGS: ReadonlySet<string> = new Set<string>([
${entries}
]);

/**
 * Cache-busting stamp, refreshed on every generation run. Because covers keep
 * stable filenames, this query param forces browsers to re-fetch the art
 * whenever it's regenerated instead of serving a stale cached image.
 */
export const COLLECTION_COVERS_VERSION = ${JSON.stringify(version)};

/** Public path to a collection's generated cover image (cache-busted). */
export function collectionCoverSrc(slug: string): string {
  return \`/brand/collections/\${slug}.webp?v=\${COLLECTION_COVERS_VERSION}\`;
}
`;
  fs.writeFileSync(MANIFEST, body);
}

async function encodeCover(bytes: Buffer, outFile: string): Promise<void> {
  await sharp(bytes)
    .resize({ width: OUT_WIDTH, withoutEnlargement: true })
    .webp({ quality: 82 })
    .toFile(outFile);
}

async function main() {
  if (FROM_FILE && SLUGS.length !== 1) {
    throw new Error("--from-file requires exactly one --slugs entry.");
  }
  if (FROM_FILE && !fs.existsSync(FROM_FILE)) {
    throw new Error(`--from-file not found: ${FROM_FILE}`);
  }

  const apiKey = FROM_FILE ? "" : requireKieApiKey();

  fs.mkdirSync(OUT_DIR, { recursive: true });

  // Purge covers for collections that are hidden from the rail, so the manifest
  // never references a tile we no longer show.
  for (const slug of RAIL_HIDDEN_SLUGS) {
    const f = path.join(OUT_DIR, `${slug}.webp`);
    if (fs.existsSync(f)) {
      fs.rmSync(f);
      console.log(`purged hidden cover: ${slug}`);
    }
  }

  let targets = flattenTaxonomy()
    .filter((n) => !RAIL_HIDDEN_SLUGS.has(n.slug))
    .map((n) => ({
      slug: n.slug,
      name: n.name,
    }));
  if (SLUGS.length) targets = targets.filter((t) => SLUGS.includes(t.slug));
  if (SLUGS.length && targets.length === 0) {
    throw new Error(
      `No matching rail collections for --slugs ${SLUGS.join(",")}.`,
    );
  }

  console.log(
    FROM_FILE
      ? `\nEncoding ${targets.length} cover(s) from ${FROM_FILE}…\n`
      : `\nGenerating covers for ${targets.length} collection(s) via Nano Banana Pro…\n`,
  );

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const [i, t] of targets.entries()) {
    const outFile = path.join(OUT_DIR, `${t.slug}.webp`);
    const label = `[${i + 1}/${targets.length}] ${t.slug}`;

    // `--from-file` is an explicit ingest: always overwrite the named slug.
    if (!FROM_FILE && !FORCE && fs.existsSync(outFile)) {
      skipped++;
      console.log(`${label} — skip (exists)`);
      continue;
    }

    if (!hasBespokeCoverTheme(t.slug)) {
      console.warn(
        `${label} — no bespoke pixel theme; using a generic fallback. Add one in scripts/lib/collection-cover-themes.ts before shipping a featured rail tile.`,
      );
    }

    if (FROM_FILE) {
      await encodeCover(fs.readFileSync(FROM_FILE), outFile);
      created++;
      console.log(`${label} — ✓ encoded from file`);
      continue;
    }

    const prompt = buildCollectionCoverPrompt(t.name, t.slug);
    let lastError: unknown;

    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
      try {
        const bytes = await generateImage(apiKey, {
          prompt,
          aspectRatio: COLLECTION_COVER_ASPECT,
          resolution: "2K",
        });
        await encodeCover(bytes, outFile);
        created++;
        console.log(
          `${label} — ✓ saved` +
            (attempt > 1 ? ` (attempt ${attempt}/${MAX_ATTEMPTS})` : ""),
        );
        lastError = undefined;
        break;
      } catch (err) {
        lastError = err;
        console.warn(
          `${label} — attempt ${attempt}/${MAX_ATTEMPTS} failed: ` +
            `${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }

    if (lastError) {
      failed++;
      console.error(
        `${label} — ✗ ${lastError instanceof Error ? lastError.message : String(lastError)}`,
      );
    }
  }

  // Manifest reflects whatever is actually on disk (accurate after partial runs).
  const onDisk = fs
    .readdirSync(OUT_DIR)
    .filter((f) => f.endsWith(".webp"))
    .map((f) => f.replace(/\.webp$/, ""));
  writeManifest(onDisk, Date.now().toString(36));

  console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  console.log(
    `  Done. Created: ${created}  Skipped: ${skipped}  Failed: ${failed}`,
  );
  console.log(`  Covers on disk: ${onDisk.length} → ${OUT_DIR}`);
  console.log(`  Manifest: ${MANIFEST}`);
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`);
  process.exit(failed > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
