import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Button,
  Hr,
  Preview,
} from "@react-email/components";
import * as React from "react";

interface MagicLinkEmailProps {
  /** The one-time, single-use sign-in URL generated by Better Auth. */
  url: string;
  /** Minutes until the link expires (for the disclaimer copy). */
  expiresInMinutes?: number;
}

export function MagicLinkEmail({ url, expiresInMinutes = 5 }: MagicLinkEmailProps) {
  return (
    <Html lang="en">
      <Head />
      <Preview>Your secure sign-in link for Y2KASE ✨</Preview>
      <Body style={bodyStyle}>
        <Container style={containerStyle}>
          {/* Header */}
          <Section style={headerStyle}>
            <Text style={wordmarkStyle}>Y2KASE</Text>
            <Text style={taglineStyle}>kawaii · y2k · holographic</Text>
          </Section>

          {/* Body */}
          <Section style={contentStyle}>
            <Text style={greetingStyle}>Sign in to Y2KASE ✨</Text>
            <Text style={paraStyle}>
              Tap the button below to securely sign in. No password needed —
              this magic link signs you in instantly. 🌸
            </Text>

            <Button href={url} style={ctaStyle}>
              Sign in to Y2KASE →
            </Button>

            <Text style={smallStyle}>
              This link expires in {expiresInMinutes} minutes and can only be
              used once. If the button doesn&apos;t work, copy and paste this URL
              into your browser:
            </Text>
            <Text style={urlStyle}>{url}</Text>

            <Hr style={hrStyle} />

            <Text style={smallStyle}>
              🔒 If you didn&apos;t request this email, you can safely ignore it —
              no one can access your account without this link.
            </Text>
            <Text style={smallStyle}>
              Questions? Email us at{" "}
              <a href="mailto:hello@y2kase.com" style={linkStyle}>
                hello@y2kase.com
              </a>
            </Text>
          </Section>

          {/* Footer */}
          <Section style={footerStyle}>
            <Text style={footerTextStyle}>
              © {new Date().getFullYear()} Y2KASE · All rights reserved
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

export default MagicLinkEmail;

// ── Styles ────────────────────────────────────────────────────────────────────

const bodyStyle: React.CSSProperties = {
  backgroundColor: "#fdf3fb",
  fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  margin: 0,
  padding: "24px 0",
};

const containerStyle: React.CSSProperties = {
  maxWidth: "560px",
  margin: "0 auto",
  backgroundColor: "#ffffff",
  borderRadius: "20px",
  border: "1px solid #f1d3ec",
  overflow: "hidden",
};

const headerStyle: React.CSSProperties = {
  background:
    "linear-gradient(120deg,#ffc2ea 0%,#e6c5ff 33%,#c4e2ff 66%,#c4ffe8 100%)",
  padding: "36px 32px 28px",
  textAlign: "center",
};

const wordmarkStyle: React.CSSProperties = {
  fontSize: "28px",
  fontWeight: "900",
  color: "#ff3ea5",
  letterSpacing: "0.06em",
  margin: 0,
  lineHeight: "1",
  textShadow: "-1px -1px 0 #fff,1px -1px 0 #fff,-1px 1px 0 #fff,1px 1px 0 #fff",
};

const taglineStyle: React.CSSProperties = {
  fontSize: "11px",
  color: "#34203b",
  letterSpacing: "0.18em",
  textTransform: "uppercase",
  margin: "6px 0 0",
  opacity: 0.7,
};

const contentStyle: React.CSSProperties = {
  padding: "36px 40px 28px",
};

const greetingStyle: React.CSSProperties = {
  fontSize: "22px",
  fontWeight: "800",
  color: "#34203b",
  margin: "0 0 16px",
};

const paraStyle: React.CSSProperties = {
  fontSize: "15px",
  color: "#34203b",
  lineHeight: "1.65",
  margin: "0 0 20px",
};

const ctaStyle: React.CSSProperties = {
  display: "block",
  background: "#ff3ea5",
  color: "#ffffff",
  fontWeight: "800",
  fontSize: "15px",
  textDecoration: "none",
  borderRadius: "9999px",
  padding: "14px 32px",
  textAlign: "center",
  margin: "0 auto 24px",
  boxShadow: "0 4px 0 #d62f88",
};

const hrStyle: React.CSSProperties = {
  borderColor: "#f1d3ec",
  margin: "0 0 24px",
};

const smallStyle: React.CSSProperties = {
  fontSize: "13px",
  color: "#34203b",
  opacity: 0.65,
  lineHeight: "1.6",
  margin: "0 0 10px",
};

const urlStyle: React.CSSProperties = {
  fontSize: "12px",
  color: "#ff3ea5",
  wordBreak: "break-all",
  margin: "0 0 16px",
};

const linkStyle: React.CSSProperties = {
  color: "#ff3ea5",
  fontWeight: "700",
};

const footerStyle: React.CSSProperties = {
  background: "#f7e7f6",
  padding: "16px 32px",
  textAlign: "center",
};

const footerTextStyle: React.CSSProperties = {
  fontSize: "11px",
  color: "#34203b",
  opacity: 0.5,
  margin: "0 0 4px",
};
